### ISSUE TITLE
Negative Value

### ISSUE THREAD

**Issue by caturkrida16** [micfun123/twos-complement#3]
I read 2's complement theory in internet, and after do 2's complement the value will be a negative. 
In your library after do 2's complement the value is not negative, is it safe? Can i just multiply the output with negative?

**Comment by micfun123** [comment]
my two compliments library just takes a standard binary string and turns it to a negative two complement. this can then get added to a normal binary number for subtraction before being converted back. Its a small school project so i would not expect it to work well for any projects of importants

**Comment by caturkrida16** [comment]
Okey thanks for the explaining
